INSERT INTO users (name, age) VALUES ("Steve", 23);
INSERT INTO users (name, age) VALUES ("Bob", 24);
INSERT INTO users (name, age) VALUES ("Ray", 25);
INSERT INTO users (name, age) VALUES ("Billy", 26);
INSERT INTO users (name, age) VALUES ("Jean", 27);
INSERT INTO users (name, age) VALUES ("David", 28);
INSERT INTO users (name, age) VALUES ("Steve", 29);
INSERT INTO users (name, age) VALUES ("Steve", 30);
INSERT INTO users (name, age) VALUES ("Steve", 23);
INSERT INTO users (name, age) VALUES ("Steve", 23);
INSERT INTO users (name, age) VALUES ("Steve", 23);
INSERT INTO users (name, age) VALUES ("Steve", 23);
INSERT INTO users (name, age) VALUES ("Steve", 23);
INSERT INTO users (name, age) VALUES ("Steve", 23);
INSERT INTO users (name, age) VALUES ("Steve", 23);
INSERT INTO users (name, age) VALUES ("Steve", 23);
INSERT INTO users (name, age) VALUES ("Steve", 23);
INSERT INTO users (name, age) VALUES ("Steve", 23);
INSERT INTO users (name, age) VALUES ("Steve", 23);
INSERT INTO users (name, age) VALUES ("Steve", 23);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cool Project", "Cars", "100000", "1/1/18", "12/31/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cool Project", "Cars", "100000", "1/1/18", "12/31/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cool Project", "Cars", "100000", "1/1/18", "12/31/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cool Project", "Cars", "100000", "1/1/18", "12/31/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cool Project", "Cars", "100000", "1/1/18", "12/31/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cool Project", "Cars", "100000", "1/1/18", "12/31/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cool Project", "Cars", "100000", "1/1/18", "12/31/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cool Project", "Cars", "100000", "1/1/18", "12/31/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cool Project", "Cars", "100000", "1/1/18", "12/31/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cool Project", "Cars", "100000", "1/1/18", "12/31/2018");

INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
